openapi: 3.0.3

# info
info:
  title: Swagger Test
  description: tagsとsecurityについて
  version: 1.0.11
  
# サーバー(今回server response見ないため使わない)
  
# タグ
tags:
  - name: dish
    description: 皿
  
paths:
  /dish/{id}:
    get:
      tags: 
        - dish
      summary: 皿情報取得
      description: idを指定して取得
      operationId: findByDishId
      parameters:
        - name: id
          in: path
          description: id指定
          required: true
          schema: 
            type: integer
            format: int64
      responses:
        '200':
          description: seccess
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                    format: int64
                    minimum: 0
                    example: 77
                  name:
                    type: string
                    example: testName
                  modified:
                    type: string
                    format: date-time
                    example: 1997-07-16T9:20:30+01:00
                  is_deleted:
                    type: boolean
                    example: false
        '400':
          description: Invalid ID supplied
        '404':
          description: Dish not found
      security:
      # readを指定
        - oauth2: [read]
        
# セキュリティをグローバルに設定
security:
  - dish_bearer_auth: []
  - basic_auth: []
  - open_id_connected: []
          
components:
  securitySchemes:
    dish_bearer_auth:
      type: http
      scheme: bearer
    basic_auth:
      type: http
      scheme: basic
    api_key_auth:
      type: apiKey
      in: header
      name: X-API-Key
    open_id_connected:
      type: openIdConnect
      openIdConnectUrl: https://example.com
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: dish read access
      
      
      
      
      